### ISSUE TITLE
data type issue

### ISSUE THREAD

**Issue by lulu-ivy** [Collert/AmazingSbuxTipsCalc#2]
Looks like on line 54 of app.py there's a reference to the variable named `time`, which is a `str`, but it needs to be cast to a `float` in order to add it to `total_hours`. My partner loves this little app and that was a pretty small fix that got the page up and working again. Thanks!

**Comment by Collert** [comment]
Hi. Thanks for pointing this out! I must have broken it when I tried to implement the latest feature and forgot to fix it since. Expect it to be up in the next couple of days.

**Comment by Collert** [comment]
The issue has been fixed. The app is back online and fully operational
